setup_yang

path_model_vgg_m = 'data/models/imagenet-vgg-m.mat';
dcnn.name = 'dcnnfv' ;
dcnn.opts = {...
     'type', 'dcnn', ...
     'model', path_model_vgg_m, ...
     'layer', 13, ...
     'numWords', 64, ...
     'encoderType', 'fv'};

os_train('dataset', 'mit', 'seed', 2, 'encoders', {dcnn}, ...
         'prefix', 'exp01', 'suffix', 'dcnn', 'printDatasetInfo', 1,...
         'writeResults', true, 'vocDir', 'data/VOC2007',...
         'useGpu', true, 'gpuId', 3);

%[opts, imdb] = os_setup('dataset', 'mit', 'seed', 1, 'encoders', {dcnn}, 'prefix', 'exp01', 'suffix', 'dcnn', 'printDatasetInfo', 1, 'writeResults', true, 'vocDir', 'data/VOC2007', 'useGpu', true, 'gpuId', 1);
%save('yang_mit.mat')
